# Generated by Django 4.2.28 on 2026-02-12 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='B-CLUB', max_length=100)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('theme_color', models.CharField(default='#eab308', max_length=7)),
                ('table_a_color', models.CharField(default='#10b981', max_length=7)),
                ('table_b_color', models.CharField(default='#3b82f6', max_length=7)),
                ('rate_base', models.IntegerField(default=150)),
                ('rate_reduced', models.IntegerField(default=135)),
                ('threshold_mins', models.IntegerField(default=15)),
                ('floor_min', models.IntegerField(default=1000)),
                ('floor_mid', models.IntegerField(default=1500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='BarOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Anonyme', max_length=100)),
                ('items', models.JSONField(default=list)),
                ('total_price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commande bar',
                'verbose_name_plural': 'Commandes bar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BilliardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(choices=[('A', 'Table A'), ('B', 'Table B')], max_length=1, unique=True)),
                ('name', models.CharField(default='Table', max_length=50)),
                ('color', models.CharField(default='#10b981', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Table de billard',
                'verbose_name_plural': 'Tables de billard',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('icon', models.CharField(default='🍹', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article inventaire',
                'verbose_name_plural': 'Articles inventaire',
            },
        ),
        migrations.CreateModel(
            name='PS4Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🎮', max_length=10)),
                ('player_options', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jeu PS4',
                'verbose_name_plural': 'Jeux PS4',
            },
        ),
        migrations.CreateModel(
            name='PS4TimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('minutes', models.IntegerField()),
                ('price', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='counter.ps4game')),
            ],
            options={
                'verbose_name': 'Option de temps PS4',
                'verbose_name_plural': 'Options de temps PS4',
            },
        ),
        migrations.CreateModel(
            name='PS4Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('players', models.IntegerField(default=1)),
                ('duration_minutes', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.ps4game')),
            ],
            options={
                'verbose_name': 'Session PS4',
                'verbose_name_plural': 'Sessions PS4',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BilliardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_identifier', models.CharField(choices=[('A', 'Table A'), ('B', 'Table B')], default='A', max_length=1)),
                ('client_name', models.CharField(default='Anonyme', max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.billiardtable')),
            ],
            options={
                'verbose_name': 'Session billard',
                'verbose_name_plural': 'Sessions billard',
                'ordering': ['-start_time'],
            },
        ),
    ]
