# Generated by Django 4.2.28 on 2026-02-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ps4timeoption',
            options={'ordering': ['minutes', 'players'], 'verbose_name': 'Option de temps PS4', 'verbose_name_plural': 'Options de temps PS4'},
        ),
        migrations.AddField(
            model_name='ps4timeoption',
            name='players',
            field=models.IntegerField(default=1),
        ),
    ]
