# Generated by Django 4.2.28 on 2026-02-14 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_alter_ps4timeoption_options_ps4timeoption_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billiardsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
